### ISSUE TITLE
斜体が斜体ではない

### ISSUE THREAD

**Issue by yumetodo** [kibousoft/mastodon#23]
https://now.kibousoft.co.jp/about/more
には

>[i]斜体[/i]

とあるが、実際には`<em>`タグが付与される。

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by ANNotunzdY** [comment]
@yumetodo 
報告ありがとうございます。
CSSでemタグに対して `font-style: italic;`  を指定しているのですが、
 `font-style: italic;` は端末によって動作しないため、WebFontの利用を検討中です。

**Comment by ANNotunzdY** [comment]
メイリオ等の環境でも斜体が表示されるよう、TypeKitを導入しました。
