### ISSUE TITLE
Twitterシェア機能において、投稿内にURLが含まれているとaタグがそのまま投稿されてしまう

### ISSUE THREAD

**Issue by ANNotunzdY** [kibousoft/mastodon#9]
![screen shot 2017-05-03 at 12 10 33](https://cloud.githubusercontent.com/assets/525548/25647047/8f980d40-2ff9-11e7-8cab-7cb5a2e53c85.png)

投稿内のaタグを除去して、URLのテキストに置換してからTwitterに渡すように修正する。

**Comment by ANNotunzdY** [comment]
@koyakei React側なので、難しければ言ってください。

**Comment by koyakei** [comment]
@ANNotunzdY 
ツイッターに流す操作方法がわからなくて困っていますが、
https://github.com/kibousoft/mastodon/blob/master/app/lib/formatter.rb#L64
ここを書き換えたら治るんじゃないかということは、見当がつきました。

**Comment by koyakei** [comment]
facebook の投稿をtwitter に投稿する機能はあるけど、それと同じものがmastodon にもあるかと思ったけど違うのかな
http://fnya.cocolog-nifty.com/blog/2017/04/mastodontwitter.html
IFTTT とか別サービスを使う必要があるわけでもないのかなぁ　よくわからない

**Comment by ANNotunzdY** [comment]
対応ありがとうございました！
